### ISSUE TITLE
Error loading plugin: unexpected EOF

### ISSUE THREAD

**Issue by mjbrender** [intelsdi-x/snap-plugin-collector-nova#7]
I `go get` the repo, build and had an issue. Here are my steps: 

```
$ go get github.com/intelsdi-x/snap-plugin-collector-nova
$ go build 
$ snapctl plugin load ./snap-plugin-collector-nova
```

Error from `snapd -t 0 -l 2` is: 

```
INFO[1062] API request                                   _module=_mgmt-rest index=18 method=GET url=/v1/tribe/agreements
INFO[1062] API response                                  _module=_mgmt-rest index=18 method=GET status=Not Found status-code=404 url=/v1/tribe/agreements
INFO[1062] API request                                   _module=_mgmt-rest index=19 method=POST url=/v1/plugins
INFO[1064] Loading plugin: /var/folders/2j/q3vl1w011yn0w4j7294btg280000gp/T/830713433/snap-plugin-collector-nova  _module=_mgmt-rest
INFO[1064] plugin load called                            _block=load _module=control
INFO[1064] plugin load called                            _block=load-plugin _module=control-plugin-mgr path=snap-plugin-collector-nova
ERRO[1064] error in getting metric types                 _block=load-plugin _module=control-plugin-mgr error=unexpected EOF plugin-type=collector
ERRO[1064] unexpected EOF                                _module=_mgmt-rest
INFO[1064] API response                                  _module=_mgmt-rest index=19 method=POST status=Internal Server Error status-code=500 url=/v1/plugins
```

Error message from `snapctl` is same as title: `Error loading plugin: unexpected EOF`

**Comment by Daniel-F-Parker** [comment]
I have had the same issue. 
I am going to post my Global config file here along with the log file of the error. 
It states the error is because of the missing "openstack_user" parameter but that is included

Logfile error:
>>>2016/08/24 16:38:17 Listening 127.0.0.1:36383
>>>2016/08/24 16:38:17 Session token AqcVoSwA0K0TZ0FlYb8kcOpBF9QfMW0NH1wg7-ug-hk=
>>>2016/08/24 16:38:17 Heartbeat started
>>>2016/08/24 16:38:17 Heartbeat timeout 1 of 3.  (Duration between checks 1.5s)
>>>2016/08/24 16:38:17 SetKey called
>>>2016/08/24 16:38:17 GetConfigPolicy called
>>>2016/08/24 16:38:17 GetConfigPolicy called
>>>2016/08/24 16:38:17 GetMetricTypes called
>>>2016/08/24 16:38:17 Recover from panic: plugin initalization failed : [Cannot find openstack_user in Global Config]
>>>2016/08/24 16:38:17 Stack of 4096 bytes: goroutine 13 [running]:
github.com/intelsdi-x/snap/control/plugin.catchPluginPanic(0xc8201ac500)
        /snapbuild/build/collector/nova/src/github.com/intelsdi-x/snap/control/plugin/plugin.go:436 +0xa9
panic(0x876280, 0xc8204b9dd0)
        /gonative/go/src/runtime/panic.go:443 +0x4e9
github.com/intelsdi-x/snap-plugin-collector-nova/novaplugin.(*NovaPlugin).init(0xc8201be300, 0x8fb4c0, 0xc8204b9870, 0x0, 0x0)
        /snapbuild/build/collector/nova/src/github.com/intelsdi-x/snap-plugin-collector-nova/novaplugin/plugin.go:291 +0x21c
github.com/intelsdi-x/snap-plugin-collector-nova/novaplugin.(*NovaPlugin).GetMetricTypes(0xc8201be300, 0xc8204b9870, 0x0, 0x0, 0x0, 0x0, 0x0)
        /snapbuild/build/collector/nova/src/github.com/intelsdi-x/snap-plugin-collector-nova/novaplugin/plugin.go:230 +0x90
github.com/intelsdi-x/snap/control/plugin.(*collectorPluginProxy).GetMetricTypes(0xc8203749c0, 0xc82041d2c0, 0x9b, 0x9b, 0xc820426420, 0x0, 0x0)
        /snapbuild/build/collector/nova/src/github.com/intelsdi-x/snap/control/plugin/collector_proxy.go:64 +0x39f
reflect.Value.call(0x85c880, 0x89b6a8, 0x13, 0x9327e0, 0x4, 0xc820425ed8, 0x3, 0x3, 0x0, 0x0, ...)
        /gonative/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x85c880, 0x89b6a8, 0x13, 0xc820425ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
        /gonative/go/src/reflect/value.go:303 +0xb1
net/rpc.(*service).call(0xc8200c3080, 0xc8201aa200, 0xc8204b8b10, 0xc82036e600, 0xc820375460, 0x7c2820, 0xc8204263e0, 0x197, 0x7a9260, 0xc820426420, ...)
        /gonative/go/src/net/rpc/server.go:383 +0x1c2
created by net/rpc.(*Server).ServeCodec
        /gonative/go/src/net/rpc/server.go:477 +0x49d

goroutine 1 [chan receive]:
github.com/intelsdi-x/snap/control/plugin.Start(0xc8201be280, 0x7fabbdbe20d8, 0xc8201be300, 0x7fff52b9a67c, 0x69, 0x0, 0x0, 0x0)
        /snapbuild/build/collector/nova/src/github.com/intelsdi-x/snap/control/plugin/plugin.go:388 +0xa73
main.main()
        /snapbuild/build/collector/nova/src/github.com/intelsdi-x/snap-plugin-collector-nova/main.go:33 +0xdb

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /gonative/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 6 [IO wait]:
net.runtime_pollWait(0x7fabbdc629b0, 0x72, 0x0)
        /gonative/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820371c60, 0x72, 0x0, 0x0)
        /gonative/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820371c60, 0x0, 0x0)
        /gonative/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820371c00, 0x0, 0x7fabbdc62b88, 0xc820374e00)
        /gonative/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200d8020, 0xc820091f60, 0x0, 0x0)
        /gonative/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200d8020, 0x0, 0x0, 0x0, 0x0)
        /gonative/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/intelsdi-x/snap/control/plugin.Start.func2(0x7fabbdc61a08, 0xc8200d8020)
        /snapbuild/build/collector/nova/src/github.com/intelsdi-x/snap/control/plugin/plugin.go:370 +0x2b
created by github.com/intelsdi-x/snap/control/plugin.Start
        /snapbuild/build/collector/nova/src/github.com/intelsdi-x/snap/control/plugin/plugin.go:376 +0x8ae

goroutine 7 [sleep]:
time.Sleep(0x59682f00)
        /gonative/go/src/runtime/time.go:59 +0xf9
github.com/intelsdi-x/snap/control/plugin.(*SessionState).heartbeatWatch(0xc8201d6240, 0xc8201c80c0)
        /snapbuild/build/collector/nova/src/github.com/intelsdi-x/snap/control/plugin/session.go:219 +0x4dd
created by github.com/intelsdi-x/snap/control/plugin.Start
"/tmp/snap-plugin-collector-nova.log" [readonly] 76L, 4687C      

-------------------------------------------------------------------------------------------------
Global config:
`{
  "log_level": 3,
  "control": {
    "plugins": {
      "collector": {
        "neutron": {
          "all": {
            "openstack_auth_url": "http://10.243.18.40",
            "openstack_user": "admin",
            "openstack_password": "password",
            "openstack_tenant": "admin"
           }
         }
       },
      "publisher": {},
      "processor": {}
    }
  },
  "tribe": {
    "enable": false
  }
}
`

**Comment by daria-lewandowska** [comment]
unexpected EOF appears mostly when your config file is wrong, Iza make new PR [here](https://github.com/intelsdi-x/snap-plugin-collector-nova/pull/9) and update cfg.json to newest version of this file, so you should do the same and your plugin will start correctly

**Comment by jcooklin** [comment]
Adding to what @daria-lewandowska stated... it's an indication that the plugin panicked indicating that error handling needs to be improved.

**Comment by IzabellaRaulin** [comment]
@mjbrender or @Daniel-F-Parker - could you confirm if this issue still occurs  - please use updated exemplary global config (already merged) and just adjust it to your setup.

**Comment by mjbrender** [comment]
I agree with @daria-lewandowska and @jcooklin that error handling needs improvement. I don’t have an environment to verify it, but thanks for keeping me posted. I’ll keep following the thread.
